blank_issues_enabled: true
contact_links:
  - name: Feature Proposal/Request
    url: https://tuneinsight.com/lattigo/contact
    about: We do not use GitHub Issues for features proposals or requests. If you have a proposal or would like to make a request for a feature, please contact us directly.
  - name: General Question
    url: https://github.com/tuneinsight/lattigo/discussions
    about: Ask a question that is not necessarily related to the use or implementation of the library.
